# SynFlow/SynFlow/SCD/__init__.py
from .freq import (
    count_keyword_tokens_by_period,
    freq_all_slots_by_period,
    freq_all_slots_by_period_normalized_token_counts,
    freq_all_slots_by_period_relative,
    freq_top_union_slots_by_period,
    plot_freq_top_union_sfillers_by_period,
    plot_freq_top_union_slots_by_period,
)

from .distdist import (
    COSINE_DISTANCE,
    DISTDIST_MEASURES,
    JSD,
    TVD,
    DistDist,
    cal_cosine_distance,
    cal_cosine_distance_contrib,
    cal_jsd,
    cal_jsd_contrib,
    cal_tvd,
    cal_tvd_contrib,
    compute_consecutive_dist_df,
    compute_period_period_dist,
    compute_weighted_consecutive_dist_df,
    multiply_consecutive_dist_saturating_support,
    permutation_test_consecutive_dist,
    plot_all_dists_by_period,
    plot_dist_by_period,
    plot_items_dist_contrib_by_period,
    plot_period_period_dist,
    plot_permutation_test_consecutive_dist,
    print_dist_contrib_by_period,
    resolve_distdist,
    sfillers_dist_contrib_by_period,
    summarize_fdr_correction,
)

__all__ = [
    # freq
    "count_keyword_tokens_by_period",
    "freq_all_slots_by_period",
    "freq_all_slots_by_period_normalized_token_counts",
    "freq_all_slots_by_period_relative",
    "freq_top_union_slots_by_period",
    "plot_freq_top_union_sfillers_by_period",
    "plot_freq_top_union_slots_by_period",

    # distribution distances
    "COSINE_DISTANCE",
    "DISTDIST_MEASURES",
    "JSD",
    "TVD",
    "DistDist",
    "cal_cosine_distance",
    "cal_cosine_distance_contrib",
    "cal_jsd",
    "cal_jsd_contrib",
    "cal_tvd",
    "cal_tvd_contrib",
    "compute_consecutive_dist_df",
    "compute_period_period_dist",
    "compute_weighted_consecutive_dist_df",
    "multiply_consecutive_dist_saturating_support",
    "permutation_test_consecutive_dist",
    "plot_all_dists_by_period",
    "plot_dist_by_period",
    "plot_items_dist_contrib_by_period",
    "plot_period_period_dist",
    "plot_permutation_test_consecutive_dist",
    "print_dist_contrib_by_period",
    "resolve_distdist",
    "sfillers_dist_contrib_by_period",
    "summarize_fdr_correction",
 
]
